##Reading in data
training.data.raw <- read.csv("C:/Users/Chris Liti/Desktop/R Data/train.csv",header=T,na.strings=c(""))
head(training.data.raw)

##missimg values
sapply(training.data.raw,function(x) sum(is.na(x)))

##unique values
sapply(training.data.raw, function(x) length(unique(x)))

##visualizing missing values
library(Amelia)
missmap(training.data.raw, main = "Missing values vs observed")

##Dropping unnecesary variables
data <- subset(training.data.raw,select=c(2,3,5,6,7,8,10,12))

##Taking care of missing values
data$Age[is.na(data$Age)] <- mean(data$Age,na.rm=T)

##seeing how variables have been coded
contrasts(data$Sex)
contrasts(data$Embarked)
##omit the rows with embarked missing
data <- data[!is.na(data$Embarked),]
head(data)
rownames(data) <- NULL
head(data)
dim(data)


##MODEL FITTING
train <- data[1:800,]
test <- data[801:889,]

model <- glm(Survived ~.,family=binomial(link='logit'),data=train)
summary(model)


##analysing table of deviance
anova(model, test="Chisq")

##PREDICTION
fitted.results <- predict(model,newdata=subset(test,select=c(2,3,4,5,6,7,8)),type='response')
fitted.results
fitted.results <- ifelse(fitted.results > 0.5,1,0)
fitted.results
##RESULTS
table(predicted=fitted.results,actual=test$Survived)
misClasificError <- mean(fitted.results != test$Survived)
misClasificError
print(paste('Accuracy',1-misClasificError))

##ROC CURVE-The ROC is a curve generated by plotting the 
##true positive rate (TPR) against the false positive rate (FPR) 
library(ROCR)
p <- predict(model, newdata=subset(test,select=c(2,3,4,5,6,7,8)), type="response")
pr <- prediction(p, test$Survived)

prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)
auc <- performance(pr, measure = "auc")
auc
auc <- auc@y.values[[1]]
auc
